CREATE USER C##DIEGOSP
IDENTIFIED BY DIEGOSP1234
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 20M ON USERS; -- Cambiado a USERS_TABLE como ejemplo

GRANT SYSDBA TO C##DIEGOSP;

/*----------XTablas----------*/
DROP TABLE Personas CASCADE CONSTRAINTS;
DROP TABLE Clientes CASCADE CONSTRAINTS;
DROP TABLE Empleados CASCADE CONSTRAINTS;
DROP TABLE telefonosPersona CASCADE CONSTRAINTS;
DROP TABLE Ventas CASCADE CONSTRAINTS;
DROP TABLE DetallesVentas CASCADE CONSTRAINTS;
DROP TABLE Productos CASCADE CONSTRAINTS;
DROP TABLE Repuestos CASCADE CONSTRAINTS;
DROP TABLE Motos CASCADE CONSTRAINTS;
DROP TABLE Accesorios CASCADE CONSTRAINTS;
DROP TABLE DetallesCompras CASCADE CONSTRAINTS;
DROP TABLE Compras CASCADE CONSTRAINTS;
DROP TABLE Proveedores CASCADE CONSTRAINTS;
DROP TABLE telefonosProveedores CASCADE CONSTRAINTS;
