--Seguridad
CREATE ROLE PA_CLIENTE_UBER1;
GRANT SELECT, INSERT, UPDATE, DELETE ON pqrs TO PA_CLIENTE_UBER1;
GRANT SELECT, INSERT, UPDATE, DELETE ON anexos TO PA_CLIENTE_UBER1;
GRANT SELECT ON pqrsrespuestas TO PA_CLIENTE_UBER1;

CREATE ROLE PA_ANALISTA_CLIENTES_UBER1;
GRANT SELECT ON pqrs TO PA_ANALISTA_CLIENTES_UBER1;
GRANT SELECT ON anexos TO PA_ANALISTA_CLIENTES_UBER1;
GRANT SELECT, INSERT, UPDATE, DELETE ON pqrsrespuestas TO PA_ANALISTA_CLIENTES_UBER1;


GRANT ALL ON pqrs TO bd1000093114; 
GRANT ALL ON anexos TO bd1000093114; 
GRANT ALL ON pqrsrespuestas TO bd1000093114; 

GRANT ALL ON pqrs TO bd1000093739; 
GRANT ALL ON anexos TO bd1000093739; 
GRANT ALL ON pqrsrespuestas TO bd1000093739; 

SELECT * FROM SESSION_ROLES;
SELECT * FROM SESSION_PRIVS;
EXECUTE DBMS_SESSION.SET_ROLE('PA_CLIENTE_UBER1');
EXECUTE DBMS_SESSION.SET_ROLE('PA_ANALISTA_CLIENTES_UBER1');