/*-----------XDisparadores-----------------*/
/*-----Adicion-----*/
DROP TRIGGER TR_SOLICITUDES_FECHA_CREACION_BI;
DROP TRIGGER TR_FECHA_VIAJE_BI;
DROP TRIGGER TR_ESTADO_PENDIENTE_BI;
DROP TRIGGER TR_SOLICITUDES_POSICIONES_BI;
DROP TRIGGER TR_SOLICITUDES_ACTIVAS_BI;
DROP TRIGGER TR_VIAJE_PRECIO_NULL_BI;

/*-----Modificacion-----*/
DROP TRIGGER TR_SOLICITUDES_ACTUALIZACION_VERIFICAR_BU;
DROP TRIGGER TR_SOLICITUDES_MODIFICACION_FECHA_PRECIO_BU;
DROP TRIGGER TR_SOLICITUDES_MODIFICACION_VIAJE_BU;
DROP TRIGGER TR_ESTADO_MODIFICACION_NO_CANCELADA_BU;

/*-----Eliminacion-----*/
DROP TRIGGER TR_SOLICITUDES_ELIMINAR_BF;

/*-----------XDisparadores-----------------*/
/*-----Adicion-----*/
DROP TRIGGER TR_PQRS_TICKED_BF;
DROP TRIGGER TR_PQRS_TICKED_BF_JU;
DROP TRIGGER TR_PQRS_RADICACION_BF;
DROP TRIGGER TR_PQRS_ESTADO_BF;

/*-----Modificacion-----*/
DROP TRIGGER TR_M_PQRS_ESTADO_BF;
DROP TRIGGER TR_M_PQRS_ESTADO_FECHA_BF;
DROP TRIGGER TR_M_PQRS_FECHA_RADICACION_BF;
DROP TRIGGER TR_M_PQRS_ANEXOS_BF;


/*-----Eliminacion-----*/
DROP TRIGGER TR_PQRS_ELIMINAR_BF;
DROP TRIGGER TR_PQRS_ELIMINAR_ANEXOS_BF;
