/*---------------------------------------------CICLO 1: XTablas---------------------------------------------*/
DROP TABLE vehiculos CASCADE CONSTRAINTS;
DROP TABLE conductores CASCADE CONSTRAINTS;
DROP TABLE tarjetasClientes CASCADE CONSTRAINTS;
DROP TABLE tarjetas CASCADE CONSTRAINTS;
DROP TABLE anexos CASCADE CONSTRAINTS;
DROP TABLE pqrsrespuestas CASCADE CONSTRAINTS;
DROP TABLE pqrs CASCADE CONSTRAINTS;
DROP TABLE requerimientos CASCADE CONSTRAINTS;
DROP TABLE solicitudes CASCADE CONSTRAINTS;
DROP TABLE posiciones CASCADE CONSTRAINTS;
DROP TABLE clientes CASCADE CONSTRAINTS;
DROP TABLE personas CASCADE CONSTRAINTS;